# Etapa 1: Imagem base com o runtime do .NET 8
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 80

# Etapa 2: Imagem do SDK do .NET 8 para compilar a aplicação
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["EcommerceAPI/EcommerceAPI.csproj", "EcommerceAPI/"]
RUN dotnet restore "EcommerceAPI/EcommerceAPI.csproj"
COPY . .
WORKDIR "/src/EcommerceAPI"
RUN dotnet build "EcommerceAPI.csproj" -c Release -o /app/build

# Etapa 3: Publicação do projeto
FROM build AS publish
RUN dotnet publish "EcommerceAPI.csproj" -c Release -o /app/publish

# Etapa 4: Imagem final com a aplicação
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "EcommerceAPI.dll"]
